#!/bin/sh

runKtlintFormat() {
  echo "-------------------------"
  echo " Running ktlintFormat... "
  echo "-------------------------"
  ./gradlew ktlintFormat --daemon
  status=$?

  if [ $status -ne 0 ]
  then
    echo "!!--!!-!!--!!-!!--!!-!!--!!-!!--!!-!!--!!--!!--!!--!!--!!"
    echo " Something went wrong. Please check logs and fix issues."
    echo "!!--!!-!!--!!-!!--!!-!!--!!-!!--!!-!!--!!--!!--!!--!!--!!"
    exit 1
  fi

  echo "--------------------------------------------------"
  echo " ktlintFormat is done. Please try to commit again."
  echo "--------------------------------------------------"
  exit 1
}

echo "-----------------------"
echo " Running ktlintCheck..."
echo "-----------------------"
./gradlew ktlintCheck --daemon

status=$?

[ $status -ne 0 ] && runKtlintFormat
exit 0
