
name: Build

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Lint
        id: ktlint
        run: ./gradlew ktlintCheck

      - name: Build
        id: build
        run: ./gradlew assemble

      - name: Test
        id: unit_test
        run: ./gradlew testDebugUnitTest

      - name: Slack failure report
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.ACTIONS_SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_MESSAGE: ":x: Job failed."

      - name: Slack success report
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.ACTIONS_SLACK_WEBHOOK }}
          SLACK_COLOR: "#15d40f"
          SLACK_MESSAGE: ":white_check_mark: All the checks succeeded."

  slack_failure_report:
    needs: build
    if: always() && needs.build.result == 'failure'
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.ACTIONS_SLACK_WEBHOOK }}

    steps:
      - name: Notify failure to slack
        uses: 8398a7/action-slack@v3
        with:
          text: ":x: Build failed."
          status: failure
          fields: repo,message,author,action,workflow,took,pullRequest
          mention: 'here'
          if_mention: always